development:
    :hostname_public: "localhost:4000"
    :to: aymeric.austral@yahoo.com

test:
    :hostname_public: "olgadays.synology.me:8081"
    :to: aymeric.austral@yahoo.com

production:
    :hostname_public: "olgadays.synology.me:8081"
    :to: aymeric.austral@yahoo.com